---
collections:
        - name: fedora.linux_system_roles
          version: 1.15.2
        - name: community.general
          version: 3.8.3
          # we use latest versions in this lab
        - name: https://github.com/sap-linuxlab/community.sap_launchpad.git
          type: git
        - name: https://github.com/sap-linuxlab/community.sap_install.git,rhpds
          type: git
        - name: https://github.com/sap-linuxlab/community.sap_operations.git
          type: git
