---
# Phase 3 - step B
#
# The role sap_hana_install unpacks the software in {{ sap_hana_install_software_directory }}
# Then it calls the installation of SAP HANA with the configured paramters

- name: Phase 3-B - Install Hana
  hosts: hanas
  become: true

  tasks:

    - name: execute the SAP Hana Installation
      include_role:
        name: community.sap_install.sap_hana_install
